# -*- coding: utf-8 -*-
"""work2.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10cF9LkVKIqJ9IdODeDW1VJQiVWWgziYO
"""



number =int(input())
if number%2 == 0:
  print(number,"is an even number.")
else:
  print(number,"is not an even number.")