# -*- coding: utf-8 -*-
"""work2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UNvOl_BjjPHznfyI_HpZC5R9HMTSm0o7
"""

r= float(input('請輸入半徑'))

PI = 3.14159

圓周長 = 2 * PI * r

圓面積 = r * r * PI

print('圓周長為', 圓周長, '圓面積為', 圓面積)