# -*- coding: utf-8 -*-
"""work2.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jf1qu2WTCGbMuCbSdbex4QfsSiloYOnF
"""

name=input("your name")
age=int(input("your age"))
height=float(input("your height"))
color=input("your favorite color")
output=("{}, {}歲, 身高{}米, 喜愛的顏色是{}。")